### ISSUE TITLE
Scroll top moves button in mobile devices

### ISSUE THREAD

**Issue by danielcaldas** [vfeskov/vanilla-back-to-top#5]
Hey there reporting a bug that seems to happen only in real mobile devices. The steps to replicate are the following:
1. Scroll down a bit on the viewport
2. Scroll top a bit on the viewport
3. You'll notice that the button is not entirely visible as you can see in the picture below.

This issue can be replicated accessing https://goodguydaniel.com/jekyll/update/2018/08/12/about-js-conf-eu-berlin-2018.html.

Cool component btw. Thanks.

![bug](https://user-images.githubusercontent.com/11733994/44006771-2eeb2eea-9e8a-11e8-9447-7e017c228991.jpg)

**Comment by MatthewMcD** [comment]
Just added this to my site (Hugo based) and it works fine on my iPhone.

![file](https://user-images.githubusercontent.com/7558738/45600962-d30a4c80-b9ca-11e8-8803-22fc390145bc.png)

**Comment by vfeskov** [comment]
@danielcaldas i check your website and i think you managed to fix it on your end. please tell if there are any other issues

**Comment by danielcaldas** [comment]
To be honest, I don't remember the exact fix for this issue 😄 , I remember I re-wrote the integration script at the time, the code is the following:

```javascript
(function configureBackToTopButton() {
    var VANILLA_BACK_TO_TOP = "https://unpkg.com/vanilla-back-to-top@7.1.14/dist/vanilla-back-to-top.min.js";
    var BTN_STYLE = {
        diameter: 42,
        backgroundColor: "#000",
        textColor: "#fff"
    };

    function addButton(style) {
        addBackToTop(style);
    }

    var script = document.createElement("script");

    script.type = "text/javascript";
    script.src = VANILLA_BACK_TO_TOP;
    script.onload = addButton.bind(this, BTN_STYLE);

    document.body.appendChild(script);
})();
```
