### ISSUE TITLE
ease is not a function

### ISSUE THREAD

**Issue by vesper8** [vfeskov/vanilla-back-to-top#7]
Hi there,

Installed your script via npm and am using it with Vue.. works great!

Trying to customize the options and noticed two things. First of all in your "options" page you use equal signs instead of semi-colons

Secondly, two of the options don't seem to work.. ease and size

the "defaults" for those are "inOutSine" and "diameter". If I put those in quotes, single or double, it just doesn't work. I get "ease is not a function"

And if I put them without quotes I get "inOutSine" and "diameter" is not defined

I suppose you could store a function within a variable and pass that as the ease function, but I don't think this is what you intended? You should be able to just pass it the name of the easing from https://www.npmjs.com/package/ease-component as you write? Could you explain how that works please?

Thanks!

**Comment by vfeskov** [comment]
it doesn't accept a string but a reference to a function

the source code of `ease-component` package is: https://github.com/component/ease/blob/master/index.js

you can copy any of the functions directly from the source and paste it into your `addBackToTop` call:
```
addBackToTop({
  ease: function inOutElastic(n){
    var s, a = 0.1, p = 0.4;
    if ( n === 0 ) return 0;
    if ( n === 1 ) return 1;
    if ( !a || a < 1 ) { a = 1; s = p / 4; }
    else s = p * Math.asin( 1 / a ) / ( 2 * Math.PI );
    if ( ( n *= 2 ) < 1 ) return - 0.5 * ( a * Math.pow( 2, 10 * ( n -= 1 ) ) * Math.sin( ( n - s ) * ( 2 * Math.PI ) / p ) );
    return a * Math.pow( 2, -10 * ( n -= 1 ) ) * Math.sin( ( n - s ) * ( 2 * Math.PI ) / p ) * 0.5 + 1;
  }
})
```

**Comment by sun2ii** [comment]
@vfeskov that doesn't seem to be a fix.

Here is my code:

```
<script>
addBackToTop({ 
  backgroundColor : '#27de70', 
  ease: 'inOutSine', 
  scrollDuration : 1000
})
</script>
```

Here is the error that I get: 

`Uncaught TypeError: p is not a function at o (vanilla-back-to-top.min.js:1)`
