### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by bosconb** [vfeskov/vanilla-back-to-top#8]
i'm using a hugo site, after adding ur install code to <body> in layouts HTML,nothing happened, i've no idea what's wrong, here's one of my page url,It would be nice if check it.thank a lot

**Comment by vfeskov** [comment]
your website uses custom scroll bar and scrolling happens unconventionally, not with `overflow:scroll|auto`

`vanilla-back-to-top` only [changes `scrollTop` property of the `scrollContainer`](https://github.com/vfeskov/vanilla-back-to-top/blob/master/index.js#L137), you can fork and change that code to interact with your custom scrolling library correctly
